sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.4"
  - "3.4.5"
  - "3.4.6"
  - "3.4.7"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - npm install uglify-js
  - haxelib dev uglifyjs .

script:
  - haxe test.hxml

deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./releaseHaxelib.sh $HAXELIB_PWD
    on:
      tags: true